### PR TITLE
New remote invoker & fixes

### PR DESCRIPTION
**Pull request by JosepSampe**
- Added new remote invoker
- Fixed issue when using IAM #237 
- Fixed python 3.7 Dockerfile #235 
- Changed default global timeout to None #209 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by omerb01** [comment]
@JosepSampe does this PR include adding a 10min timer for each action? so `get_result()` won't wait forever for actions that got OOM

**Comment by JosepSampe** [comment]
> @JosepSampe does this PR include adding a 10min timer for each action? so `get_result()` won't wait forever for actions that got OOM

No, with current invoker it is not easy to do so. I need to think how to do it with the minor number of changes

**Comment by omerb01** [comment]
a minor suggestion - it is much more convenient to get information about actions that got "global" timeout (of `get_result()`) , can you insert prints of activations that aren't done? (instead of print only the number of undone activations)

**Comment by JosepSampe** [comment]
> @JosepSampe a minor suggestion - it is much more convenient to get information about actions that got "global" timeout (of `get_result()`) , can you insert prints of activations that aren't done? (instead of print only the number of undone activations)

Do you mean to print also activation IDs?

**Comment by omerb01** [comment]
@JosepSampe yep

**Comment by gilv** [comment]
@JosepSampe is it ready to merge?

**Comment by JosepSampe** [comment]
@gilv Yes ;)

**Pull request merged**
