### PR TITLE
Add function_name to future's status

### PR DESCRIPTION
**Pull request by omerb01**
with this minor change we can know from which function the future came from and its runtime memory.
I found it useful for diagnosing PyWren results.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by JosepSampe** [comment]
@omerb01 Just as a suggerence ;) (maybe I'm missing something) Why not set this information directly to the future through invoke_status (host_job_meta)(https://github.com/pywren/pywren-ibm-cloud/blob/master/pywren_ibm_cloud/executor.py#L130) instead of sending it to the cloud and then return back to the future through status?

**Comment by omerb01** [comment]
@JosepSampe I have seen that everything related to a future's status is implemented in that way so I added my changes there.
as I understood, we update `run.status` parameter only at this point: https://github.com/pywren/pywren-ibm-cloud/blob/5a9ff8d3fdbd5da5d8308833b98332ddcccb5096/pywren_ibm_cloud/future.py#L149

I can deliver `runtime_memory` and `function_name` locally in several ways, but I don't see how to do it on the right place. how do you suggest to do so?

**Comment by JosepSampe** [comment]
@omerb01 My question is: Do you need this values in `run_status`? What if they are in `invoke_status` instead?
https://github.com/pywren/pywren-ibm-cloud/blob/5a9ff8d3fdbd5da5d8308833b98332ddcccb5096/pywren_ibm_cloud/future.py#L72

**Comment by omerb01** [comment]
@JosepSampe Thanks! didn't noticed we have `invoke_status` ;)

**Comment by JosepSampe** [comment]
@omerb01 If you need `runtime_memory` or `func_memory` in `invoke_status`, it is also in Executor:
https://github.com/pywren/pywren-ibm-cloud/blob/9374e1732f17ffd219a3f9613be563e158fee166/pywren_ibm_cloud/executor.py#L48

**Pull request merged**
