### PR TITLE
Improved runtime management

### PR DESCRIPTION
**Pull request by JosepSampe**
1. This patch allows to introduce the desired runtime memory in the executor. For example:

`pw = pywren.ibm_cf_executor(runtime_memory=128)`

If the variable `runtime_memory `is not set, PW uses the memory set in the config file (Default=256MB)

Also, it is possible to provide memory size in the deployment script:

```
./deploy_runtime --memory 256
./deploy_runtime clone ibmfunctions/pywren-metabolomics:3.6 --memory 1024
```
or:
```
import pywren_ibm_cloud as pywren
pywren.runtime.clone_runtime('ibmfunctions/pywren-metabolomics:3.6', memory=256)
```

2. With this pacth, it is no lonnger necessary to clone any runtime before using it, since PyWren internally does the job the first time you use a new one. Therefore, this command is no longer necessary previous to use a personalized runtime:

```
pywren.runtime.clone_runtime('ibmfunctions/pywren-metabolomics:3.6')
```
Instead, you can specify thee desired runtime and memory size in the executor itself:

```
pw = pywren.ibm_cf_executor(runtime='ibmfunctions/pywren-metabolomics:3.6', runtime_memory=256)
...
```

3. This patch includes in PyWren three different default runtimes: one for Python3.5, one for Python3.6 and one for Python3.7. Now PyWren automatically detects the Python version of the client and deploys the appropriate runtime. So If no runtime specified in `pw = pywren.ibm_cf_executor()`, PyWren automatically deploys the default runtime the first time you use it. Thus, in Watson Studio is no longer necessary to clone the Python3.5 runtime before using it. Also, it is possible to use differnt memory configurations with the default runtime, for example:
```
import pywren_ibm_cloud as pywren
pw = pywren.ibm_cf_executor(runtime_memory=128)
```

4. Tested and working with Python 3.7

5. Actions are now grouped into packages in CF dashboard: https://cloud.ibm.com/openwhisk/actions. So it is easy to delete legacy PyWren runtimes by simply eliminating old PyWren version packages:
dashboard

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe Wow :) and only 31 files were changes ;) Is this ready or you still working on it?

**Comment by gilv** [comment]
@JosepSampe why you removed .gitignore ? It's common to have such file in open source projects...so the git status doesnt' show all kind of files we don't need to commit by mistake

**Comment by JosepSampe** [comment]
@gilv

**Comment by JosepSampe** [comment]
@gilv It is all ready

**Comment by gilv** [comment]
@JosepSampe interesting... i thought those .gitignore are standard...let's then ignore the gitignore

**Comment by JosepSampe** [comment]
> @JosepSampe interesting... i thought those .gitignore are standard...let's then ignore the gitignore

@gilv I took a look to other github projects and seems that most of them have the .gitignore. So I added some lines into the one you uploaded and I'm going to restore it ;)

**Comment by idoyehe** [comment]
@gilv Can you please review it and merge it tomorrow I would like to use that for the experiments...

Thank you!

**Comment by idoyehe** [comment]
@JosepSampe @gilv 
Hi all,

I created my customized action that installing fasttext... and I deploy it using the script runtime/deploy_runtime with create and memory flags...

but now I don't success to invoke those specific actions as I did before... just pass their names to the PyWren executor, now it is trying to install them although they are exists

image

**Comment by JosepSampe** [comment]
@idoyehe can you post here an example of how you create the executor?

**Comment by idoyehe** [comment]
`        pywren_executor = pywren.ibm_cf_executor(runtime="idoye@fasttext-hyperparameters", runtime_memory=2048)`

**Comment by JosepSampe** [comment]
@idoyehe it works for me. You have to specify the runtime_name as it is, no how it is stored in CF, becasue CF does not allow '/' and ':' characters, so I had to modify them by '@' and '_':
`pw = pywren.ibm_cf_executor(runtime="idoye/fasttext-hyperparameters", runtime_memory=2048)`

Also, it is always great to add a tag to the docker image with the python version, for example: `idoye/fasttext-hyperparameters:3.7` ;)

**Comment by idoyehe** [comment]
> @idoyehe it works for me. You have to specify the runtime_name as it is, no how it is stored in CF, becasue CF does not allow '/' and ':' characters, so I had to modify them by '@' and '_':
> `pw = pywren.ibm_cf_executor(runtime="idoye/fasttext-hyperparameters", runtime_memory=2048)`
> 
> Also, it is always great to add a tag to the docker image with the python version, for example: `idoye/fasttext-hyperparameters:3.7` ;)

OK. I will do it

Thanks!

**Pull request merged**
