### PR TITLE
Compute abstraction

### PR DESCRIPTION
**Pull request by JosepSampe**
More changes about Storage and Compute backends abstraction.
- Code refactoring that allows to groups all logic of the compute backend in its own folder, making pywren more generic.

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe can you short summary the changes here?

**Comment by JosepSampe** [comment]
@gilv Basically is code refactoring to make PyWren even more abstracted from compute backends. 

Now, all the specific compute backend logic is located within one unique folder (`compute/backends/`), and the rest of the PyWren code is fully abstracted. For example, in IBM CF all the specific logic is in: `compute/backends/ibm_cf/` folder. Thus, to add more compute backneds it is only required to add all the logic within `compute/backends/compute_backend_name`, and there is no need to modify anything else in the rest of the PyWren code

**Comment by gilv** [comment]
@JosepSampe it's a bit hard to review it in details, only 31 ;) files...so I Can I merge it as is ? or it's WIP?
Another question, should we address comments form Lachlan in separate pull request or in this one?

**Comment by JosepSampe** [comment]
@gilv You can already merge it ;) I think it will be better to address Lachlan comments in another pull request as they are not related to this one.

**Comment by gilv** [comment]
@omerb01 please update master branch ;) we have 31 files changed.. ;)

**Pull request merged**
