### PR TITLE
Added max req. attempts in COS client

### PR DESCRIPTION
**Pull request by JosepSampe**
- Added max request attempts when creating a COS client. Default set to 5
- Fixed exception handling in future class
- Added logic to detect running activations
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe can i merge it or it still in wip?

**Comment by JosepSampe** [comment]
@gilv ready

**Comment by gilv** [comment]
@JosepSampe I wonder, if this will resolve the issue, how we can know it worked? Is there way to write new status of such invocation, like "success-with-retry", etc? At the end of pywren job it will be very good to know how many invocations were retried by cos client.. we need this information at least at first stages, we can remove it at later phase.

**Comment by gilv** [comment]
@JosepSampe i also managed to use this patch and get stuck on get_results, perhaps some invocation got out of memory, json was not written and it got stuck on get_result as before

**Comment by JosepSampe** [comment]
@gilv I already have the patch to prevent get_result stuck forever when using COS. I'm doing final tests ;)

**Comment by gilv** [comment]
@JosepSampe thanks...and what is your input on this:

@JosepSampe I wonder, if this will resolve the issue, how we can know it worked? Is there way to write new status of such invocation, like "success-with-retry", etc? At the end of pywren job it will be very good to know how many invocations were retried by cos client.. we need this information at least at first stages, we can remove it at later phase.

**Comment by omerb01** [comment]
@JosepSampe just a question to understand this patch better. now every failed request with `ibm_cos` or `internal_storage` will retry 5 times max, so we don't need in any case a wrapper "try&catch" mechanism right?

**Comment by JosepSampe** [comment]
@omerb01 This was an attempt to configure ibm_boto3 client to retry COS requests when they fail. However, seems that is has no effect for the  "client disconnect" issue we experience with embl. https://github.com/IBM/ibm-cos-sdk-python/issues/32

In another PR I added the try&except logic to handle this issue in the pywren IBM COS wrapper, but it only works for `internal_storage. So you still need try&except block in your code if you use `ibm_cos` function parameter.

**Pull request merged**
