### PR TITLE
Code refactor & New local_executor

### PR DESCRIPTION
**Pull request by JosepSampe**
- Preliminar code refactor needed for #209 (Does not include #209)
- Fixed issue #220 
- Added new local_executor() to run PyWren jobs in the local machine leveraging all the local CPU Cores
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by omerb01** [comment]
@JosepSampe so now new invoker runs on a separate process as described #209 ?

**Comment by JosepSampe** [comment]
> @JosepSampe so now new invoker runs on a separate process as described #209 ?

@omerb01 No, this is a preliminar refactor needed for #209, but it does not include #209.
@gilv this one can be already merged. I I will submit #209 in another pull request once I finished it, since I'm trying different implementations, and I have to deeply test them and decide which one is better.

**Comment by gilv** [comment]
@JosepSampe is this ready to merge?

**Comment by JosepSampe** [comment]
@gilv Yes, ready to merge

**Pull request merged**
