### PR TITLE
Improved runtime deployment & remote invocation

### PR DESCRIPTION
**Pull request by JosepSampe**
This patch improves runtime deployment, abstracting memory parameter, so issues #133 and #136 are fixed. Changes in the deployment script:

- Changed **create** command to **build** (as we are building a new docker image runtime)
- Changed **clone** command to **create** (as in fact we are not cloning anything, but creating a new runtime in our namespace)
- **build** and **update** commands will update all the actions based on the docker image in the namespace, so it is no longer necessary to specify the memory in the script.

Other changes:
1. Added Dockerfiles for Python3.5 and Python3.7. Dockerfile for Python3.6 simplified.
2. When a new runtime is deployed, now it takes into account the region and the namespace. So it prevents some possible issues if someone changes CF region but keeps PyWren COS bucket.

-------

Also, improved remote invocation mechanism.
Current Remot Invocation plot:
ri_now

With this patch:
ri_3 7

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by omerb01** [comment]
@JosepSampe Does `build` command also update the source code in addition to docker's environment?

**Comment by JosepSampe** [comment]
@omerb01 Yep, it updates everything ;)

**Comment by gilv** [comment]
@JosepSampe it was fast ;)

**Comment by JosepSampe** [comment]
@gilv Yep ;) It is already merged (only 1 minor conflict). And all aligned with master branch

**Pull request merged**
