### PR TITLE
Add support for Google Cloud Storage

### PR DESCRIPTION
**Pull request by tomwhite**
As a part of work I've been doing to get [Dask running on Pywren](https://github.com/tomwhite/dask-executor-scheduler) I've written storage and compute backends for Google Cloud Storage and Cloud Run. This is the PR for the storage backend, which I'd like to contribute to this project.

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@tomwhite thank you very much! We will review it and merge. Out of curiosity, what  compute backend you are using with Google Cloud Storage?

**Comment by tomwhite** [comment]
@gilv thanks for taking a look. I've written a Google Cloud Run backend that I've successfully used with the GCS storage backend. I'll submit a separate PR for that soon.

**Comment by gilv** [comment]
@tomwhite we will soon integrate many other backends into this project. @JosepSampe what are the other backends you developed? Is Google Cloud Run there also?

**Comment by JosepSampe** [comment]
@gilv We have storage+compute backends for AWS S3+Lambda, Azure Functions+Azure Storage, Alibaba Fn+Storage, and we also have Google Functions+this Google Storage backend, but not the Google Cloud Run

**Comment by tomwhite** [comment]
@JosepSampe that's great! When do you plan to merge them? I'd be happy to try out the GCP backend.

**Comment by gilv** [comment]
@tomwhite Did you tried IBM Cloud Functions? ;)

**Comment by tomwhite** [comment]
No, I haven't :)

Thanks for merging this.

**Comment by gilv** [comment]
@tomwhite then take free trial...and you will be surprised how fast it is

**Pull request merged**
