### PR TITLE
Add support to generate execution timeline plots

### PR DESCRIPTION
**Pull request by JosepSampe**
Created built-in method that generates execution timeline plots in a specified folder.

How to use?
Map:
```
pw = pywren.ibm_cf_executor()
futures = pw.map(my_map_function, range(200))
result pw.get_result()
pw.create_timeline_plots(dst='/home/jsampe/desktop', name='testmap')
```

Map-Reduce: (need to return statuses from reduce, for now)
```
pw = pywren.ibm_cf_executor()
futures = pw.map(my_map_function, range(200), my_reduce_function)
result = pw.get_result()
pw.create_timeline_plots(dst='/home/jsampe/desktop', name='testmapreduce',
                         result['run_statuses'], result['invoke_statuses'] )
```
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe will this work to create timeline in cloud object storage? To use 'dst' point to some bucket, object name.

**Comment by JosepSampe** [comment]
@gilv At this moment it creates the plots in a local directory (dst), but we can add an option to load the plots into COS.

**Comment by gilv** [comment]
@JosepSampe you suggest to add cos support plots in a different pull request or add it here? In Watson Studio for example, the only way to generate plots is to use COS as a target

**Comment by JosepSampe** [comment]
@gilv I think it would be better to merge this one, and then I will add support to store these plots into COS.

**Pull request merged**
