### PR TITLE
Installation script to support PW version as a parameter

### PR DESCRIPTION
**Pull request by JosepSampe**
Installation script now supports PyWren version as an input parameter, for example:
`./install_pywren 1.0.2`
or
`curl -fsSL "https://git.io/fhe9X" | sh /dev/stdin 1.0.2`
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe thanks a lot..this is great. Two questions, if version doesn't provided as an input then it will fetch the latest one, as it works today right? This will ./install_pywren fetch latest release?

How complicated is to support also ./install_pywren master ? So it will fetch master branch?
Thanks

**Comment by gilv** [comment]
@JosepSampe i merge it..thanks.  If it's not complicated, please add support for `./install_pywren master `

**Comment by JosepSampe** [comment]
@gilv seems that it already supports `./install_pywren master` ;)

**Comment by gilv** [comment]
@JosepSampe great :) By the way, when we execute ./install_pywren ? I don't see this in documentation at all.. thanks

**Comment by JosepSampe** [comment]
We execute the script here: `curl -fsSL "https://git.io/fhe9X" | sh`.
`install_pywren.sh` is hidden behind this url: https://git.io/fhe9X

**Pull request merged**
