### PR TITLE
Runtime deployment logic fully moved into pywren package

### PR DESCRIPTION
**Pull request by JosepSampe**
With this patch, the runtime deploy_utils are fully integrated in the pywren package when it is installed.

Till now, the only way to deploy a runtime (create, clone, default) was to have the full repository cloned in the client machine. Then, when a user wanted to clone a runtime from the code (including a notebook), he had to:

```
import pywren_ibm_cloud as pywren

from pywren_ibm_cloud.deployutil import clone_runtime
clone_runtime('ibmfunctions/pywren-metabolomics:3.6', config, 'pywren-ibm-cloud')

pw = pywren.ibm_cf_executor(config=config, runtime='pywren-metabolomics_3.6')
...
```

Now, it is not necessary to keep the cloned git repository in the local machine, as all the tools necessary to deploy a runtime are integrated in the pywren package. Thus, we can simple do:

```
import pywren_ibm_cloud as pywren
pywren.runtime.clone_runtime('ibmfunctions/pywren-metabolomics:3.6')
pw = pywren.ibm_cf_executor(runtime='pywren-metabolomics_3.6')
...
```

or from a notebook (including watson studio):
```
import pywren_ibm_cloud as pywren
pywren.runtime.clone_runtime('ibmfunctions/pywren:3.5', config)
pw = pywren.ibm_cf_executor(runtime='pywren_3.5', config=config)
...
```

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe this is great... i need a bit time to realize the issues that might happen since this addtion is not backward compatible. Will merge then.

**Comment by gilv** [comment]
@JosepSampe with this approach, how to clone the default run time? or the procedure the same for default also?

import pywren_ibm_cloud as pywren
pywren.runtime.clone_runtime('ibmfunctions/default-runtime:3.6')
pw = pywren.ibm_cf_executor(runtime='default-runtime_3.6')

**Comment by gilv** [comment]
@JosepSampe or even simpler, is it possible to deploy default run time with this aporach?
so far we used ./deploy_runtime

**Comment by gilv** [comment]
@JosepSampe it doesn't work

pywren.runtime.clone_runtime('ibmfunctions/pywren-metabolomics:3.6', config)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-b1e103e10db4> in <module>
----> 1 pywren.runtime.clone_runtime('ibmfunctions/pywren-metabolomics:3.6', config)

AttributeError: module 'pywren_ibm_cloud.runtime' has no attribute 'clone_runtime'

**Comment by JosepSampe** [comment]
> @JosepSampe with this approach, how to clone the default run time? or the procedure the same for default also?
> 
> import pywren_ibm_cloud as pywren
> pywren.runtime.clone_runtime('ibmfunctions/default-runtime:3.6')
> pw = pywren.ibm_cf_executor(runtime='default-runtime_3.6')

@gilv You can simply execute: `pywren.runtime.deploy_default_rutime()`
Checking last issue...

**Comment by JosepSampe** [comment]
> @JosepSampe it doesn't work
> 
> pywren.runtime.clone_runtime('ibmfunctions/pywren-metabolomics:3.6', config)
> 
> AttributeError Traceback (most recent call last)
> in 
> ----> 1 pywren.runtime.clone_runtime('ibmfunctions/pywren-metabolomics:3.6', config)
> 
> AttributeError: module 'pywren_ibm_cloud.runtime' has no attribute 'clone_runtime'

@gilv I created a new clean VM (ubuntu based), and installed PyWren through `pip3 install pywren-ibm-cloud` and everything worked fine, including: `pywren.runtime.clone_runtime('ibmfunctions/pywren-metabolomics:3.6')`. Also tested in my machine where I have the whole git repo, and all is ok. 

Do you have everything updated?

**Comment by gilv** [comment]
@JosepSampe right...my fault. I did refresh to notebook, it proceed but failed on the other step

Cloning docker image ibmfunctions/pywren-metabolomics:3.6
IBM Cloud Functions init for Namespace: pywren_dev_us_east
IBM Cloud Functions init for Host: https://us-east.functions.cloud.ibm.com
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-10-b1e103e10db4> in <module>
----> 1 pywren.runtime.clone_runtime('ibmfunctions/pywren-metabolomics:3.6', config)

~/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/deploy_utils.py in clone_runtime(image_name, config)
    126     _create_zip_action()
    127     _extract_modules(image_name, cf_client, config)
--> 128     _create_blackbox_runtime(image_name, cf_client)
    129 
    130     print('All done!')

~/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/deploy_utils.py in _create_blackbox_runtime(image_name, cf_client)
     83 
     84     # Upload zipped PyWren action
---> 85     with open(ZIP_LOCATION, "rb") as action_zip:
     86         action_bin = action_zip.read()
     87     cf_client.create_action(runtime_name, code=action_bin, kind='blackbox', image=image_name)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/gilv/Documents/metaspace/notebook/ibmcf_pywren.zip'

**Comment by JosepSampe** [comment]
@gilv ok! Going to test it with local notebooks. In Watson Studio it works fine :)

**Comment by gilv** [comment]
@JosepSampe i think i know what is wrong...perhaps the fact that i did restructure and no more "pywren' folder exists...will fix it

**Comment by JosepSampe** [comment]
@gilv In this pull request I already deleted any static reference to that folder you deleted. 
Now I could reproduce the error with a local notebook, fixing it ;)

**Comment by JosepSampe** [comment]
@gilv I think I found the origin of issue. In my case I got same error because I didn't have the `zip` package installed on my new VM, so I ran 'sudo apt install zip' and everything worked fine. Do you have "zip" package installed?

**Comment by gilv** [comment]
@JosepSampe i think the problem with the create_zip function deploy_utils... I removed "pywren" folder, that script is not updated...currious how it worked for you with problematic script

**Comment by gilv** [comment]
@JosepSampe I actually not sure anymore...may be i messed that script... I don't know, bottom line doesn't work for me, getting 

FileNotFoundError: [Errno 2] No such file or directory: '/Users/gilv/Documents/metaspace/notebook/ibmcf_pywren.zip'

Will try to better debug it

**Comment by gilv** [comment]
I do have zip installed

**Comment by JosepSampe** [comment]
@gilv Since you created the pip package, I no longer use that script anymore. In fact we can delete it.

New way to install pywren from a notebook is:
`!{sys.executable} -m pip install -U pywren-ibm-cloud`

I recently explained it in pull #107

**Comment by gilv** [comment]
@JosepSampe I removed "pywren" folder...
so this script is not correct seems

    if not os.path.isfile(pywren_location + '/../__main__.py'):
	        copyfile(pywren_location + '/action/__main__.py', pywren_location + '/../__main__.py')
	    cmd = 'cd ' + pywren_location + '/..; zip -FSr ' + ZIP_LOCATION + ' __main__.py pywren_ibm_cloud/ -x "*__pycache__*"'
	
pywren_location already ends with "..", so adding '/../__main__.py will get to the main Python sites-packages

**Comment by JosepSampe** [comment]
The script is correct, 
pywren location comes from:
```
def _get_pywren_location():
    my_location = os.path.dirname(os.path.abspath(__file__))
    pw_location = os.path.join(my_location, '..')
    return pw_location
```
**my_location** is the path of the `deploy_utils.py` file, that is, it gets where PyWren is installed + the path of the deploy_utils.py file, wich is, for example in my computer: `/home/josep/data/eclipse-workspace/pywren-ibm-cloud/pywren_ibm_cloud/runtime`, so if we add at the end '..', then **pywren_location** is` /home/josep/data/eclipse-workspace/pywren-ibm-cloud/pywren_ibm_cloud`. 

One located where the main package is installed, then it copies the `__main__.py` file one directory behind in order to create the zip.

It's very strange why you cannot run it, because I ran the script in every possible place and it worked form me, even with a new VM, Watson studio, conda environment, etc...

**Comment by JosepSampe** [comment]
@gilv Maybe in your case the user does not have permissions to write the **\__main\__.py** file into the sites-packages. 

I already have a new approach where it is not necessary to copy the **\__main\__.py** file. I can directly pack it into the **.zip** avoiding to copy it into **sites-packages**.

**Comment by gilv** [comment]
@JosepSampe if you run it with pip install then pywren location is 
/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/..
so there are issues with the script

**Comment by gilv** [comment]
@JosepSampe where is the new approach ? ;)

**Comment by gilv** [comment]
@JosepSampe still doesn't work for me...i think it depends which directory contains the notebook...
did 

#Install PyWren-IBM
!{sys.executable} -m pip install -U pywren-ibm-cloud
import pywren_ibm_cloud as pywren

pywren.runtime.clone_runtime('ibmfunctions/pywren-metabolomics:3.6', config)

got:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-10-b1e103e10db4> in <module>
----> 1 pywren.runtime.clone_runtime('ibmfunctions/pywren-metabolomics:3.6', config)

~/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/deploy_utils.py in clone_runtime(image_name, config)
    126     _create_zip_action()
    127     _extract_modules(image_name, cf_client, config)
--> 128     _create_blackbox_runtime(image_name, cf_client)
    129 
    130     print('All done!')

~/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/deploy_utils.py in _create_blackbox_runtime(image_name, cf_client)
     83 
     84     # Upload zipped PyWren action
---> 85     with open(ZIP_LOCATION, "rb") as action_zip:
     86         action_bin = action_zip.read()
     87     cf_client.create_action(runtime_name, code=action_bin, kind='blackbox', image=image_name)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/gilv/Documents/CloudButton EU project/metaspace/notebook/ibmcf_pywren.zip'

**Comment by gilv** [comment]
@JosepSampe the same problem...FileNotFoundError: [Errno 2] No such file or directory:

**Comment by JosepSampe** [comment]
@gilv The method is executed correctly? add some prints to see **ZIP_LOCATION** and **pywren_location**, because if the `raise Exception('Unable..)` is not executed, this means that the .zip should be created.

**Comment by gilv** [comment]
@JosepSampe somehow after a bit of Whiskey i finally realized why it didn't worked... ;)
This method 

pywren.runtime.clone_runtime('cactusone/pywren-dev:3.6', config)

will fail if you run Jupyter notebook from a folder that contain spaces in the name...
"zip" will fail if folder has spaces and warnig is printed "zip warning: name not matched:"...

**Comment by JosepSampe** [comment]
@gilv wow... interesting 👍

**Comment by JosepSampe** [comment]
@gilv By befault **ZIP_LOCATION** points to where you are calling the `clone_runtime()` method. For example, if you run de deployment script from the runtime dir: `./deploy_runtime`, it creates the .zip in the runtime folder (as usual previous to this pull request). 

In your case, as you executed the **jupyter notebook** command from `/Users/gilv/Documents/CloudButton EU project/metaspace/notebook/`, it tries to create the .zip in this location. I think you can avoid the issue of white spaces by running the **jupyter notebook** command from `/Users/gilv/Documents`, and then navigate to the location of your notebook.

I tried to point the **ZIP_LOCATION** to **/tmp/ibmcf_pywren.zip**. However, Watson Studio does not allow to create anything in /tmp, so I finally coded this previous approach.

**Comment by gilv** [comment]
@JosepSampe the space is separator for "zip", so in my case it tried to create zip into "/Users/gilv/Documents/CloudButton" and tried to add "EU", "project" as files..
interesting...

**Pull request merged**
