### PR TITLE
 Added data_limit config param

### PR DESCRIPTION
**Pull request by JosepSampe**
- Added data_limit config param according to #286 
- Increased internal knative timeout for #287 
- Fixed memory peak measurement
- Allow build default knative runtimes locally. This should help in #283
- Now knative builds the default runtime based on the current python version
- OOM errors are now correctly raised from knative

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by JosepSampe** [comment]
@gilv WIP, not ready to merge

**Comment by JosepSampe** [comment]
@gilv ready ;)

**Comment by omerb01** [comment]
@JosepSampe Tested everything you detailed and added comments in the relevant post.
also, I ran all CF tests successfully.

**Comment by omerb01** [comment]
@JosepSampe minor thing that I have just discovered:
when testing simple hello world program:
```python
import pywren_ibm_cloud as pywren

def my_func(args):
    print('Hello World')

pw = pywren.ibm_cf_executor(log_level='DEBUG')
futures = pw.map(my_func, range(3))
results = pw.get_result()
```
I expect from PyWren to measure the memory peak cause `log_level='DEBUG'`, but it actually doesn't do that.
if I pass `extra_env={'SHOW_MEMORY_PEAK': 'True'}`, it works fine.

**Comment by JosepSampe** [comment]
@omerb01 This was already deleted in 1.5.1 due to some compatibility problems with other compute backends

**Pull request merged**
