### PR TITLE
Improved Function exception management

### PR DESCRIPTION
**Pull request by JosepSampe**
1. In this patch I improved the exception management when a function produces an exception so that PyWren only prints the exception traceback of the function, instead of the full traceback from the local pywren code. For example, currently when an exception is produced within a function, pywren shows all of this traceback:
```
Traceback (most recent call last):
  File "examples/rabbitmq_monitor.py", line 51, in <module>
    results = pw.get_result()
  File "/home/josep/data/eclipse-workspace/pywren-ibm-cloud/pywren_ibm_cloud/wren.py", line 387, in get_result
    WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/home/josep/data/eclipse-workspace/pywren-ibm-cloud/pywren_ibm_cloud/wren.py", line 323, in monitor
    pbar=pbar, THREADPOOL_SIZE=THREADPOOL_SIZE, WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/home/josep/data/eclipse-workspace/pywren-ibm-cloud/pywren_ibm_cloud/wait.py", line 83, in wait
    pbar=pbar)
  File "/home/josep/data/eclipse-workspace/pywren-ibm-cloud/pywren_ibm_cloud/wait.py", line 310, in _wait_storage
    pool.map(get_result, f_to_wait_on)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/josep/data/eclipse-workspace/pywren-ibm-cloud/pywren_ibm_cloud/wait.py", line 294, in get_result
    f.result(throw_except=throw_except, internal_storage=internal_storage)
  File "/home/josep/data/eclipse-workspace/pywren-ibm-cloud/pywren_ibm_cloud/future.py", line 295, in result
    reraise(*self._traceback)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/action/pywren_ibm_cloud/action/jobrunner.py", line 206, in run
  File "examples/rabbitmq_monitor.py", line 34, in my_function
    print(data['key'])
KeyError: 'key'
```
95% of this traceback is completely unnecessary for the users, since it shows from where the "function traceback" is reraised from the internal pywren code.

Now Pywren shows the activation ID that produced the exception, and only the traceback from the function:
```
Executor ID 8fc42196-1e46 There was an exception - Activation ID: f4c654118d514e8d8654118d515e8df3

Traceback (most recent call last):
  File "/action/pywren_ibm_cloud/action/jobrunner.py", line 203, in run
  File "examples/rabbitmq_monitor.py", line 34, in my_function
    print(data['key'])
KeyError: 'key'
```

2. Also modified the pywren remote code so that when a user doesn't put the return statement in the function (i.e, the function doesn't produce a result), then the output.pickle file is not stored in COS, preventing thus thousands of unnecessary connections against COS.

3. Improved status management when rabbitmq is activated.
 

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe is it possible to turn on  "full exception stack mode", via some flag or configuration variable?

**Comment by JosepSampe** [comment]
@gilv I think I can add previous behavior with current additions. However,  (maybe I'm missing something...) do we need that "full (local) stack" if the exception is produced within a function?

**Comment by gilv** [comment]
@JosepSampe I guess if we need to debug something in more details, then seeing full stack may assist to indentify various issues. For example in the full stack trace you used we have:

  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)


It has line numbers, having line numbers in generic packages may assist to identify if versions of those packages are not consistent with the code we running

**Comment by JosepSampe** [comment]
@gilv But in this particular case, I think that that 95% of the traceback is negligible, I mean, it does not provide any valuable information since the exception was produced within the function, and the traceback shows unneeded (and maybe confusing) lines for debugging.

If versions of those packages are not consistent with the code we running, the traceback provided from the function will show it as it is now ;) In the previous example, the traceback from the function only shows 3 lines because I raised a keyError. Another error in the function will show the full traceback as usual.

**Pull request merged**
