### PR TITLE
Minor changes in pickle

### PR DESCRIPTION
**Pull request by JosepSampe**
- Reverted exception pickling issues
- Prevent false out-of-memory errors
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe based on the input from @omerb01 this pull request has fixed the issues we had with pickles... I still had no time to test it actually. 
Can you please short summary, what was the issue with the previous code and what is your fix for this? Thanks

**Comment by JosepSampe** [comment]
@gilv Not sure what was the issue, as I fixed it before test that notebook ;)
but basically, in this fix I added `pickling_support.install()` which is used to correctly pickle tracebacks.

**Comment by gilv** [comment]
@JosepSampe interesting...then I wonder how it worked before ;)

**Comment by JosepSampe** [comment]
@gilv Those lines of code was there before. However I deleted them in a recent pull request as I though there were not necessary there.. and everything worked ok till you found this issue. This pull request was to put it back ;)

**Pull request merged**
