### PR TITLE
changed variable name: futures to ftrs

### PR DESCRIPTION
**Pull request by JosepSampe**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe we have : runtime/requirements.txt and pywren/requirements.
When i think about, why need to have both files? And if it both - should we can the same requirements?

**Comment by JosepSampe** [comment]
@gilv They are for different purposes: pywren/requirements.txt cointains all required packages to install IBM-PyWren in a local machine. Whereas runtime/requirements.txt cointains all the required packages to create a new runtime. 

In 957e32a I updated Dokcerfile an requiremnents from the main repository (https://github.com/ibm-functions). I tested them now by creating a new custom runtime based on python3.5 and it works properly.

**Comment by gilv** [comment]
@JosepSampe and should we keep them consistent with the same dependencies versions? i guess it's better have it consistent

**Comment by JosepSampe** [comment]
@gilv yep, we can keep them consistent

**Pull request merged**
