### PR TITLE
Added new optional args in the function signature

### PR DESCRIPTION
**Pull request by JosepSampe**
- Added 'obj' as an optional arg of the function to process data from COS (deleted bucket, key and data_stream args)
- Improved performance of data partitioner when keys are provided
- Added 'id' as an optional arg of the function (#192). This identifies the number of the function activation.
- Added 'rabitmq' as an optional arg of the function. It provides easy access to a rabitmq service in the same way as 'ibm_cos' arg works.
- Added a pub/sub example that shows how rabbitmq arg works to communicate 2 functions.
- Docs updated
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe is it ready to merge or you still working on it?

**Comment by gilv** [comment]
@JosepSampe various services in IBM are using cos:// scheme to access data in IBM Cloud Object Storage. I would like to have the same pattern here as well. Can you please change ibm_cos:// to cos:// ? Thanks

**Comment by JosepSampe** [comment]
> @JosepSampe various services in IBM are using cos:// scheme to access data in IBM Cloud Object Storage. I would like to have the same pattern here as well. Can you please change ibm_cos:// to cos:// ? Thanks

@gilv I'm aware of this fact, but I put `ibm_cos://` because in configuration we have `ibm_cos`, and this prefix should match the one in configuration. So maybe we should change config from `ibm_cos` to `cos` or find a way to have both. 

This prefix is a way to identify in configuration which storage backend to use, and also it makes internal pywren logic more generic. So with this we can easily operate on multiple storage backends (s3://, swift://, etc..). In any case, this prefix is optional, and if not provided pywren automatically puts `ibm_cos`.

**Comment by gilv** [comment]
@JosepSampe we also ibm_cos as initiated boto3 injected to maps... i think we need to change config to have "cos" and then have "cos://"...you are right. Can you change it? Then i will merge the code

**Comment by gilv** [comment]
@JosepSampe can we make it backward compatible? we will have new configuration "cos"...but inside PyWren code we will support also if someone put "ibm_cos" from previous versions

**Comment by JosepSampe** [comment]
@gilv Sure!

**Comment by JosepSampe** [comment]
@gilv It was easier to change than I thought. I didn't change config, so forget what I said about to change config keys. Ready to merge ;)

**Pull request merged**
