### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by omerb01**
- improve modularity
- change`result_to_compare` access from COS to an inner class member.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by omerb01** [comment]
@JosepSampe can you please review it and share your thoughts?

**Comment by JosepSampe** [comment]
@omerb01 Now for all tests that use: 
`self.assertEqual(sum(result), self.__class__.cos_result_to_compare)`

I'm getting:
```
======================================================================
FAIL: test_chunks_bucket (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/josep/data/dev-workspace/pywren-ibm-cloud/pywren_ibm_cloud/tests.py", line 367, in test_chunks_bucket
    self.assertEqual(result, self.__class__.cos_result_to_compare)
AssertionError: 291131 != 291130

======================================================================
FAIL: test_chunks_bucket_one_reducer_per_object (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/josep/data/dev-workspace/pywren-ibm-cloud/pywren_ibm_cloud/tests.py", line 384, in test_chunks_bucket_one_reducer_per_object
    self.assertEqual(sum(result), self.__class__.cos_result_to_compare)
AssertionError: 291131 != 291130

...
```

**Comment by omerb01** [comment]
@JosepSampe you need to let the test file to delete previous old files

**Comment by JosepSampe** [comment]
@omerb01 Yep, now all working fine

**Pull request merged**
