### PR TITLE
Minor tests.py fix

### PR DESCRIPTION
**Pull request by omerb01**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by omerb01** [comment]
@gilv please don't merge, until I will follow @JosepSampe 's comments on #182

**Comment by omerb01** [comment]
@gilv now it is ready to be merged

**Comment by JosepSampe** [comment]
@omerb01 My idea was, apart of the tests you added, to test also functions that return `futures` instead of `results`.

**Comment by omerb01** [comment]
@JosepSampe sorry, my mistake.
all your 3 examples on #182 doesn't work for me, I get:
```
2019-08-08 11:02:06,676 [DEBUG] pywren_ibm_cloud.executor: ServerlessExecutor created with ID: 1210-4c8b
2019-08-08 11:02:06,677 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3-api.us-geo.objectstorage.softlayer.net
2019-08-08 11:02:06,677 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: IBM COS: Using COS api_key - Requesting new token
2019-08-08 11:02:07,713 [DEBUG] pywren_ibm_cloud.libs.ibm_cloudfunctions.client: IBM CF init for namespace: pywren_dev_us_east
2019-08-08 11:02:07,714 [DEBUG] pywren_ibm_cloud.libs.ibm_cloudfunctions.client: IBM CF init for host: https://us-east.functions.cloud.ibm.com
2019-08-08 11:02:07,714 [DEBUG] pywren_ibm_cloud.libs.ibm_cloudfunctions.client: IBM CF user agent set to: python-requests/2.22.0 pywren-ibm-cloud/1.0.18-snapshot
2019-08-08 11:02:07,714 [INFO] pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf: PyWren v1.0.18-snapshot init for IBM Cloud Functions - Namespace: pywren_dev_us_east - Region: us_east
2019-08-08 11:02:07,714 [INFO] pywren_ibm_cloud.runtime.runtime: ExecutorID 1210-4c8b | JobID A000 - Selected Runtime: ibmfunctions/action-python-v3.6 - 256MB
2019-08-08 11:02:07,714 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata found in local cache
2019-08-08 11:02:07,715 [DEBUG] pywren_ibm_cloud.job.job: ExecutorID 1210-4c8b | JobID A000 - Serializing function and data
2019-08-08 11:02:07,718 [DEBUG] pywren_ibm_cloud.job.serialize: Modules to transmit: None
2019-08-08 11:02:07,718 [INFO] pywren_ibm_cloud.job.job: ExecutorID 1210-4c8b | JobID A000 - Uploading function and data
2019-08-08 11:02:08,852 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: PUT Object pywren.jobs/1210-4c8b/A000/aggdata.pickle - Size: 21.0B - OK
2019-08-08 11:02:09,296 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: PUT Object pywren.jobs/1210-4c8b/A000/func.pickle - Size: 707.0B - OK
2019-08-08 11:02:09,296 [INFO] pywren_ibm_cloud.invoker: ExecutorID 1210-4c8b | JobID A000 - Starting function invocation: return_futures_map_function3()  - Total: 1 activations
2019-08-08 11:02:09,871 [DEBUG] pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf: ExecutorID 1210-4c8b | JobID A000 - Function 00000 invocation done! (0.574s) - Activation ID: ce904055931e4bee904055931eebee92
2019-08-08 11:02:09,872 [INFO] pywren_ibm_cloud.executor: ExecutorID 1210-4c8b - Getting results...
2019-08-08 11:02:13,503 [DEBUG] pywren_ibm_cloud.future: ExecutorID 1210-4c8b | JobID A000 - Got status from Function 00000 - Activation ID: ce904055931e4bee904055931eebee92 - Time: 1.75 seconds
2019-08-08 11:02:13,504 [INFO] pywren_ibm_cloud.executor: ExecutorID 1210-4c8b - Cleaning temporary data
Traceback (most recent call last):
  File "/Users/omerbelh/Library/Application Support/IdeaIC2019.1/python-ce/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Users/omerbelh/Library/Application Support/IdeaIC2019.1/python-ce/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/omerbelh/Library/Application Support/IdeaIC2019.1/python-ce/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/omerbelh/Library/Application Support/IdeaIC2019.1/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/omerbelh/IdeaProjects/WORK/pywren-temp/main.py", line 32, in <module>
    results = pw.get_result()
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 378, in get_result
    WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 334, in monitor
    raise e
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 294, in monitor
    THREADPOOL_SIZE=THREADPOOL_SIZE, WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/monitor/wait_storage.py", line 75, in wait_storage
    THREADPOOL_SIZE=THREADPOOL_SIZE)
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/monitor/wait_storage.py", line 232, in _wait_storage
    pool.map(get_result, f_to_wait_on)
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/monitor/wait_storage.py", line 216, in get_result
    f.result(throw_except=throw_except, internal_storage=internal_storage)
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/future.py", line 224, in result
    self.status(throw_except, internal_storage)
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/future.py", line 194, in status
    unused_callgroup_id, total_new_futures = self._call_status['new_futures'].split('/')
ValueError: too many values to unpack (expected 2)
```

**Comment by gilv** [comment]
@JosepSampe can you handle it please?

**Comment by omerb01** [comment]
@JosepSampe these examples still don't work, I get the same exception errors.

**Comment by omerb01** [comment]
@JosepSampe I think something is wrong with the current implementation regrading returned futures.
when I run:
```python
import pywren_ibm_cloud as pywren

def my_map_function(x):
    def _func(x):
        return x + 1

    pw = pywren.ibm_cf_executor()
    return pw.map(_func, range(x))

pw = pywren.ibm_cf_executor()
pw.call_async(my_map_function, 3)
print(pw.get_result())
```
I get: `[1, 2, 3]`
also the monitor bar is changed during the process to monitor the map function inside the call_async function

**Comment by JosepSampe** [comment]
@omerb01 hmmm... I think you get the correct result: when a **future** or a list of **futures** are returned as a result of a function, they are transparently tracked by pywren. Is for this that the progress bar is updated.

What did you expect here?

**Comment by omerb01** [comment]
@JosepSampe I expected to get future objects instead of their outputs.
for example, it is useful when I need some info about inner executions, and if I need inner outputs, I can simply return `pw.get_result()` instead of futures.

**Comment by JosepSampe** [comment]
@omerb01 Originally it was designed to easily create sequences of functions. For example A->B->C->D. In this case, A B and C return futures and pywren transparently tracks these new futures, finally showing the result of C as the user locally called `pw.get_result()` in his machine. This is how `remote_invoker` functionality works.

The question is, if you locally call `pw.get_result()` in your machine, why you want a list of futures here? I think it makes more sense to get the final result instead of a list of futures. Common user may not be aware on how PyWren internally works and what futures are. Anyway, futures are always internally stored, so if you need them you can access them (pw.futures).

Moreover, if you return `pw.get_result()` from the function, this means that the function must wait other functions to finish (I think we should avoid this approach whenever we can), increasing the total function execution time($$). With our current approach, when you return the futures the function finishes and then the local PyWren is the responsible to track these new futures, saving thus function execution time.

What do you think?

**Comment by omerb01** [comment]
@JosepSampe thanks for the explanation, I wasn't aware of this feature and now I understand why we need it.
I've seen that there isn't `pw.futures` anymore, instead of that there is `pw.jobs` and I don't find their any inner futures, is it possible to add these futures to the main pw executor? (the very outer one)
I use these futures for statistics purposes like time calculating

**Comment by JosepSampe** [comment]
@omerb01 Yep, `pw.futures` was replaced in favor of `pw.jobs`, since with it is easier to organize futures and track the status of multiple jobs from the same executor.

Would it be nice for you to extract futures by iterating pw.jobs? something like:
```
futures = [f for job in pw.jobs for f in pw.jobs[job]['futures']]
```

**Comment by JosepSampe** [comment]
@omerb01 Well, finally I added futures variable in #193. Futures variable will contain absolutely all futures generated by the executor, so you can access it as usual ;)

**Comment by omerb01** [comment]
@gilv I will submit a PR with few addition regarding to the conversation above

**Pull request merged**
