### PR TITLE
Changes in iam_connector

### PR DESCRIPTION
**Pull request by JosepSampe**
- Moved from **tornado** library to **requests** (issue #141)
- Put `imb_iam` config dictionary into `ibm_cos` dictionary. In this way, it is not necessary to pass a new parameter each time we want to start COS backend.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe private endpoints also work with api key, there are no issues with it. What exactly you observed? thanks

**Comment by JosepSampe** [comment]
> @JosepSampe private endpoints also work with api key, there are no issues with it. What exactly you observed? thanks

@gilv Fixed. If endpoint is **http** it doesn't work with API KEY

**Comment by gilv** [comment]
@JosepSampe we need to use https:// and not http://.... seems not documented correctly

**Comment by JosepSampe** [comment]
> @JosepSampe we need to use https:// and not http://.... seems not documented correctly

Yep, it is fixed

**Pull request merged**
